### ISSUE TITLE
Page Missing

### ISSUE THREAD

**Issue by Kasandra-CSIR** [AAROC/aaroc.github.io#4]
Cool website! Well done!

Bootstrap link is missing on the home page and some services links which you probably still adding.

**Comment by brucellino** [comment]
Hi @Kasandra-CSIR thanks ! is there a page throwing a 404 (ie, missing link) or is there a page that you think *should* be there but is not ?

**Comment by Kasandra-CSIR** [comment]
The bootstrap link trys to open up www.getbootstap.io and then shows "server not found" error. 

Service links show 404 error.

>>> Bruce Becker <notifications@github.com> 26/01/2015 13:28 >>>

Hi @Kasandra-CSIR thanks ! is there a page throwing a 404 (ie, missing link) or is there a page that you think should be there but is not ? 
—
Reply to this email directly or view it on GitHub.

-- 
This message is subject to the CSIR's copyright terms and conditions, e-mail legal notice, and implemented Open Document Format (ODF) standard. 
The full disclaimer details can be found at http://www.csir.co.za/disclaimer.html. 

This message has been scanned for viruses and dangerous content by MailScanner, 
and is believed to be clean. 

Please consider the environment before printing this email. 
-- 
This message is subject to the CSIR's copyright terms and conditions, e-mail legal notice, and implemented Open Document Format (ODF) standard. 
The full disclaimer details can be found at http://www.csir.co.za/disclaimer.html.

This message has been scanned for viruses and dangerous content by MailScanner, 
and is believed to be clean.

Please consider the environment before printing this email.
